<?php

namespace Acme\LiftStuffBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RepLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepLogRepository extends EntityRepository
{
}
